# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 16:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_servicespost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name=b'img',
        ),
    ]
