# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_post_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpost',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='servicespost',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='warepost',
            name='title',
            field=models.TextField(),
        ),
    ]
