# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20181229_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqpost',
            name='head',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='head',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespost',
            name='head',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warepost',
            name='head',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faqpost',
            name=b'title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name=b'title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='servicespost',
            name=b'title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='warepost',
            name=b'title',
            field=models.CharField(max_length=150),
        ),
    ]
