# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_auto_20181229_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
