# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-29 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='warepost',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
