# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-30 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_warepost_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faqpost',
            old_name=b'body',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='faqpost',
            name='head',
        ),
        migrations.RemoveField(
            model_name='servicespost',
            name=b'body',
        ),
        migrations.RemoveField(
            model_name='servicespost',
            name=b'img',
        ),
        migrations.RemoveField(
            model_name='warepost',
            name=b'body',
        ),
        migrations.AddField(
            model_name='faqpost',
            name='question',
            field=models.CharField(default=123, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespost',
            name='sm50price',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespost',
            name='sm55price',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespost',
            name='sm60price',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespost',
            name='sm65price',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicespost',
            name='sm70price',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warepost',
            name='price',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='warepost',
            name='head',
            field=models.CharField(max_length=150),
        ),
    ]
